### ISSUE TITLE
Any way to sync with firefox?

### ISSUE THREAD

**Issue by Sparsa** [torvic9/plasmafox#21]
Is there any way to sync with mobile browsers? I use firefox sync extensively, I like this work very much. Also, I noticed that this is not available in the Arch repository or in the aur repo. Any reason for that?

**Comment by torvic9** [comment]
1) I have never used Sync, but it should work. Maybe you have to turn on `fxaccounts` in about:config.
If Sync requires a Mozilla API key (not sure), then it doesn't work because Plasmafox doesn't include any keys (possible legal implications).

2) It's not in AUR because no one put it there :-)
I use GitHub for two reasons: I already have an account here in contrast to AUR, and I can provide binary releases (the reason why Plasmafox was created in the first place, as some people complained about extra long build times).

____
N.B.: you can manually add a key by adding something like
`ac_add_options --with-mozilla-api-keyfile=${PWD@Q}/mozilla-api-key` to mozconfig
and defining the key in PKGBUILD, e.g.
`_mozilla_api_key=xxxxxxxx` 
`echo -n "$_mozilla_api_key" >mozilla-api-key`
See Arch Firefox PKGBUILD for details.

**Comment by Sparsa** [comment]
Okay so just changing some flags iassociated with fxaccoutns in the about:config saved the day. 
I will try to put up an aur for it if it is okay for you.

**Comment by torvic9** [comment]
I'm okay with that, but obviously I cannot give support over there.
Also, I don't know for how long Plasmafox will be alive as my main desktop is now Xfce, at least for the moment being. 
It's also possible that PF will switch to ESR release with v78.
And finally, I run and build PF on Manjaro testing branch, which might differ from Arch and could lead to temporary incompatibilities with system libs, but that's not a big issue imho.

So yeah, you can go ahead, just keep the above in mind.
Closing this now, feel free to reopen if the actual problem isn't fixed.

**Comment by Sparsa** [comment]
Actually I am a Manjari user only, any chance of it getting into stable? Is it up to becoming default browser for Manjari KDE?

**Comment by torvic9** [comment]
No idea - not my decision. Ask Manjaro. I'm 99% sure they won't accept it.
